# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad826e2d2a9514f7e6d37c0ad06304596013d72147cd039d939516a6320e561145a9cfa0ba89515223f487983caf388d266fa2d0723f662bd28d791391f1ebd7

test:
  secret_key_base: 2374ead28e47d9c15693236e04baa7e58ec5324564ebd31fd91b89918ed75109830a2d39aa8d9d77b98b5649a2cd2385b7a76aeaf935ca88093dfd30ac8062f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
